import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Linking, Share } from 'react-native';
import { useLocalSearchParams, router } from 'expo-router';
import { ChevronLeft, FileText, CheckCircle2, TrendingUp, Download, Share2, Wrench } from 'lucide-react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export default function ProjectDetailScreen() {
  const params = useLocalSearchParams();
  const project = params.project ? JSON.parse(params.project as string) : null;
  const [activeTab, setActiveTab] = useState('overview');

  if (!project) return <View><Text>Loading...</Text></View>;

  const uploadedDocs = [
    { title: 'Dokumen Perencanaan', file: project.docs?.perencanaan },
    { title: 'RAB (Budget Plan)', file: project.docs?.rab },
    { title: 'Gambar Kerja', file: project.docs?.gambarKerja },
  ].filter(d => d.file); // Filter if simulated

  const workItems = project.workItems || [
    { name: 'Pekerjaan Persiapan', target: '100%', progress: 50 },
    { name: 'Pekerjaan Pondasi', target: '50 m3', progress: 20 },
  ]; // Mock if empty

  const generatePDF = async () => {
    try {
      const htmlContent = `
        <html>
          <head>
            <style>
              body { font-family: Helvetica, sans-serif; padding: 20px; }
              h1 { color: #312e59; }
              .header { margin-bottom: 20px; border-bottom: 2px solid #312e59; padding-bottom: 10px; }
              .section { margin-top: 20px; }
              table { width: 100%; border-collapse: collapse; margin-top: 10px; }
              th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
              th { backgroundColor: #f2f2f2; }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>Project Report: ${project.nama}</h1>
              <p><strong>Location:</strong> ${project.lokasi}</p>
              <p><strong>Status:</strong> ${project.status}</p>
              <p><strong>Total Progress:</strong> ${project.progress}%</p>
            </div>

            <div class="section">
              <h3>Work Items Progress</h3>
              <table>
                <tr><th>Item</th><th>Target</th><th>Progress</th></tr>
                ${workItems.map((item: any) => `
                  <tr>
                    <td>${item.name}</td>
                    <td>${item.target}</td>
                    <td>${item.progress || 0}%</td>
                  </tr>
                `).join('')}
              </table>
            </div>

            <div class="section">
              <h3>Recent Updates</h3>
              <p>No recent updates logged in this session.</p>
            </div>
            
            <div class="section">
              <p style="color: grey; font-size: 10px;">Generated by MTERP Mobile System</p>
            </div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      await Sharing.shareAsync(uri);
    } catch (e) {
      console.log(e);
    }
  };

return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <ChevronLeft color="#1E293B" size={24} />
        </TouchableOpacity>
        <View>
          <Text style={styles.headerTitle} numberOfLines={1}>{project.nama}</Text>
          <Text style={styles.headerSub}>{project.lokasi}</Text>
        </View>
        <TouchableOpacity style={styles.pdfBtn} onPress={generatePDF}>
          <Share2 color="#312e59" size={20} />
        </TouchableOpacity>
      </View>

      <View style={styles.tabs}>
        <TouchableOpacity style={[styles.tab, activeTab === 'overview' && styles.activeTab]} onPress={() => setActiveTab('overview')}>
          <Text style={[styles.tabText, activeTab === 'overview' && styles.activeTabText]}>Overview</Text>
        </TouchableOpacity>
        <TouchableOpacity style={[styles.tab, activeTab === 'docs' && styles.activeTab]} onPress={() => setActiveTab('docs')}>
          <Text style={[styles.tabText, activeTab === 'docs' && styles.activeTabText]}>Dokumen</Text>
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={{ padding: 24 }}>
        
        {activeTab === 'overview' ? (
          <>
            {/* Progress Card */}
            <View style={styles.progressCard}>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                <Text style={{ color: '#fff', opacity: 0.8 }}>Total Progress</Text>
                <TrendingUp color="#fff" size={20} />
              </View>
              <Text style={{ color: '#fff', fontSize: 36, fontWeight: 'bold', marginVertical: 10 }}>{project.progress}%</Text>
              <View style={{ height: 6, backgroundColor: 'rgba(255,255,255,0.3)', borderRadius: 3 }}>
                <View style={{ width: `${project.progress}%`, height: '100%', backgroundColor: '#fff', borderRadius: 3 }} />
              </View>
            </View>

            {/* BUTTON GRID: Actions */}
            <View style={styles.gridAction}>
              {/* Tombol Laporan Harian */}
              <TouchableOpacity 
                style={[styles.actionBtn, { flex: 1, backgroundColor: '#10B981' }]} 
                onPress={() => router.push({ pathname: '/daily-report', params: { project: JSON.stringify(project) } } as any)}
              >
                <CheckCircle2 color="#fff" size={24} />
                <Text style={styles.actionBtnText}>Laporan Harian</Text>
              </TouchableOpacity>

              {/* Tombol Manajemen Alat (BARU) */}
              <TouchableOpacity 
                style={[styles.actionBtn, { flex: 1, backgroundColor: '#F59E0B' }]} 
                onPress={() => router.push({ pathname: '/project-tools', params: { projectId: project._id, projectName: project.nama } } as any)}
              >
                <Wrench color="#fff" size={24} />
                <Text style={styles.actionBtnText}>Alat Proyek</Text>
              </TouchableOpacity>
            </View>

            {/* Work Items List */}
            <Text style={styles.sectionTitle}>Item Pekerjaan</Text>
            {project.workItems?.map((item: any, i: number) => (
              <View key={i} style={styles.itemRow}>
                <View>
                  <Text style={styles.itemName}>{item.name}</Text>
                  <Text style={styles.itemTarget}>Target: {item.target}</Text>
                </View>
                <Text style={styles.itemVal}>{item.progress || 0}%</Text>
              </View>
            ))}
          </>
        ) : (
          <View>
             <Text style={{ textAlign: 'center', color: '#94A3B8', marginTop: 20 }}>Fitur Dokumen (Mockup)</Text>
          </View>
        )}

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 24, paddingTop: 60, backgroundColor: '#fff' },
  backBtn: { padding: 8, borderRadius: 50, backgroundColor: '#F1F5F9' },
  headerTitle: { fontSize: 18, fontWeight: 'bold', color: '#1E293B', maxWidth: 200 },
  headerSub: { fontSize: 12, color: '#64748B' },
  pdfBtn: { padding: 8 },

  tabs: { flexDirection: 'row', backgroundColor: '#fff', paddingHorizontal: 24, paddingBottom: 10 },
  tab: { marginRight: 20, paddingBottom: 10 },
  activeTab: { borderBottomWidth: 2, borderBottomColor: '#312e59' },
  tabText: { color: '#64748B', fontWeight: 'bold' },
  activeTabText: { color: '#312e59' },

  progressCard: { backgroundColor: '#312e59', padding: 20, borderRadius: 20, marginBottom: 20, shadowColor: '#312e59', shadowOpacity: 0.3, shadowRadius: 8, elevation: 5 },
  
  gridAction: { flexDirection: 'row', gap: 12, marginBottom: 24 },
  actionBtn: { alignItems: 'center', justifyContent: 'center', padding: 16, borderRadius: 16, gap: 8 },
  actionBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 12 },

  sectionTitle: { fontSize: 16, fontWeight: 'bold', color: '#1E293B', marginBottom: 12 },
  itemRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, backgroundColor: '#fff', borderRadius: 12, marginBottom: 10 },
  itemName: { fontSize: 14, fontWeight: '600', color: '#334155' },
  itemTarget: { fontSize: 12, color: '#94A3B8' },
  itemVal: { fontSize: 16, fontWeight: 'bold', color: '#312e59' },
});